// Stubbed AI assistant for the prototype. Isolated behind this one function
// so a real Claude API call can be substituted later without touching the
// controller/route layer. Responses are clearly labelled as sample content.
async function chat({ message }) {
  const reply =
    "This is a sample response from the VidaCare assistant prototype. " +
    "In this demo build, responses are not generated by a live AI model. " +
    `You said: "${message.slice(0, 200)}". ` +
    "A real assistant would offer general wellness information here — never a diagnosis or treatment instruction.";

  return {
    reply,
    isDemoResponse: true,
    disclaimer: "This assistant does not provide medical advice or diagnoses.",
  };
}

module.exports = { chat };
