const CAPABILITIES = {
  VIEW_PROFILE: "VIEW_PROFILE",
  VIEW_VITALS: "VIEW_VITALS",
  VIEW_JOURNAL: "VIEW_JOURNAL",
  VIEW_TREATMENT: "VIEW_TREATMENT",
  EDIT_TREATMENT: "EDIT_TREATMENT",
  RECEIVE_ALERTS: "RECEIVE_ALERTS",
};

const CAREGIVER_PERMISSION_COLUMN = {
  [CAPABILITIES.VIEW_PROFILE]: "canViewProfile",
  [CAPABILITIES.VIEW_VITALS]: "canViewVitals",
  [CAPABILITIES.VIEW_JOURNAL]: "canViewJournal",
  [CAPABILITIES.VIEW_TREATMENT]: "canViewTreatment",
  [CAPABILITIES.RECEIVE_ALERTS]: "canReceiveAlerts",
};

const ERROR_CODES = {
  ACCOUNT_PENDING_VERIFICATION: "ACCOUNT_PENDING_VERIFICATION",
  ACCOUNT_REJECTED: "ACCOUNT_REJECTED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

const DEMO_DATA_NOTICE =
  "Demo/sample data for prototype demonstration only. Not real patient information.";

module.exports = {
  CAPABILITIES,
  CAREGIVER_PERMISSION_COLUMN,
  ERROR_CODES,
  DEMO_DATA_NOTICE,
};
